appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: xvzuuiOVTivX7Q0wqiJM+Okzx3AKRWZevDvy39+fOV0/HdBgOp1rM/vBd6d/kNYhI4ihuw83HwP1svlqd9vtQUq/SGkMsn8rgr/L1grxrdLz6+Hrq5VcjcRnkaU+FfECtBgUFYKtRf3vtZhsBXrH6xt/nzX2BE4+NL9E0h5TuSqrhnJXynVC+QKqIESBuoLAYbRJCxg5AkfJylbvvEk2/RudrGM2sVfHdTiJOFARFJ8cGbPRb4SsvVni46oOZj5fXaGs3Zj/mT0HmU4GLvXExKh0IMaIho3h9gKE1n9EWu7y3R6c3Tkptds5z3IIVp9fNZu3qUus6Pxwn4O6uQGYJ8Mx2rttDDe52yJs0guOEUkjlINbAlwT0Ssvyoc+7W9JwK/1o63v6UCxEP/jTAgIJR+M187IysVw2doxEKPwGtocpS2lIOYRolV4c75+FsElgPCkZnmB9rucnpVPOaDG35Rm18nOqIAfujOUGzdRKbQqhWRS7IhGl0eO2CoXChWjqBP31CAaQB6neh8Z/JprgyKDsBs+96fD8chYDLb02Y6HtFYEQ1GcddoNl+OmPhxE8+T3W4lgPK7vxRBN8Zjv6vaOodsuspvheBbQ4A/+WDC96xdOWoq46ZxUjmAML0+PeOSzUrjINqxCo8B8L3XIv8NGfdv9oH9iSEv2xAyEeng=}
